default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: programmerhub_development
  username: postgres
  password: admin
  host: localhost
  port: 5432

  #
test:
  <<: *default
  database: programmerhub_test
  username: postgres
  password: admin
  host: localhost
  port: 5432
production:
  <<: *default
  database: programmerhub_production
  username: programmerhub
  password: <%= ENV['PROGRAMMERHUB_DATABASE_PASSWORD'] %>
